models/emprestimos.py
from datetime import date, datetime
from models import db

class Emprestimo(db.Model):
    __tablename__ = "tb_emprestimos"

    id = db.Column("l_id", db.Integer, primary_key=True)
    user_id = db.Column("emp_usr_id", db.Integer, db.ForeignKey("tb_usuarios.usr_id"), nullable=False)
    item_id = db.Column("emp_itm_id", db.Integer, db.ForeignKey("tb_itens.itm_id"))
    data_emprestimo = db.Column( "emp_data_emprestimo", db.DateTime, default=datetime.now)
    data_devolucao = db.Column("emp_data_devolucao",db.DateTime,nullable=True)
    status = db.Column("emp_status", db.String(20),default="pendente")  # pendente, devolvido
    user = db.relationship("User", backref="emprestimos")
    item = db.relationship("Item", backref="emprestimos")

    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()
        return  self

    @classmethod
    def get(cls, id):
        return cls.query.get(id)

    @classmethod
    def all(cls):
        return cls.query.all()

    def update(self, user_id=None, item_id=None, data_emprestimo=None, data_devolucao=None, status=None):
        
        if user_id is not None:
            self.user_id = user_id
        
        if item_id is not None:
            self.item_id = item_id
        
        if data_emprestimo is not None:
            self.data_emprestimo = data_emprestimo
        
        if data_devolucao is not None:
            self.data_devolucao = data_devolucao
        
        if status is not None:
            self.status = status
        
        db.session.commit()
        return self

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    @classmethod
    def ativos_por_usuario(cls, user_id):
        return cls.query.filter_by(user_id=user_id,status="pendente").count()

controllers/emprestimo_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from datetime import date, datetime, timezone

from decorators import admin_required
from models.emprestimos import Emprestimo
from models.users import User
from models.itens import Item
from storage import db

emprestimo_bp = Blueprint("emprestimo", __name__, url_prefix="/emprestimos", template_folder="templates/emprestimos")

@emprestimo_bp.route("/")
@login_required
def listar():

    if current_user.is_admin():
        emprestimos = Emprestimo.all()
    else:
        emprestimos = Emprestimo.query.filter_by(user_id =current_user.id).all()

    return render_template("emprestimos/emprestimos.html", emprestimos=emprestimos, User=User,Item=Item)

@emprestimo_bp.route("/adicionar", methods=["POST"])
@login_required
def adicionar():
    LIMITE_EMPRESTIMOS = 3

    item_id = request.form.get("item_id")

    if not item_id:
        flash("Item inválido.", "error")
        return redirect(url_for("item.itens"))    

    total_ativos = Emprestimo.ativos_por_usuario(current_user.id)

    if total_ativos >= LIMITE_EMPRESTIMOS:
        flash(f"Você atingiu o limite de {LIMITE_EMPRESTIMOS} empréstimos ativos.","error") 
        return redirect(url_for("item.itens"))

    item = Item.get(int(item_id))

    if not item or item.quantidade <= 0:
        flash("Item indisponível.", "error")
        return redirect(url_for("item.itens"))

    emprestimo = Emprestimo(
        user_id=current_user.id,
        item_id=item_id,
        status="pendente"
    )
    emprestimo.save()

    item.update(quantidade=item.quantidade - 1)

    flash("Empréstimo registrado com sucesso!", "success")
    return redirect(url_for("emprestimo.listar"))

@emprestimo_bp.route("/devolver/<int:id>", methods=["POST"])
@login_required
def devolver(id):
    emp = Emprestimo.get(id)
    if not emp:
        flash("Empréstimo não encontrado.", "error")
        return redirect(url_for("emprestimo.listar"))

    if emp.user_id != current_user.id:
        flash("Você não pode devolver um empréstimo de outro usuário!", "error")
        return redirect(url_for("emprestimo.listar"))

    item = Item.get(emp.item_id)
    if not item:
        flash("Item associado não encontrado!", "error")
        return redirect(url_for("emprestimo.listar"))

    emp.update(
        status="devolvido",
        data_devolucao=datetime.now()
    )

    item.update(quantidade=item.quantidade + 1)

    flash("Item devolvido com sucesso!", "success")
    return redirect(url_for("emprestimo.listar"))


@emprestimo_bp.route("/remover/<int:id>", methods=["POST"])
@admin_required
def remover(id):
    emprestimo = Emprestimo.get(id)
    if not emprestimo:
        flash("Empréstimo não encontrado.", "error")
        return redirect(url_for("emprestimo.listar"))

    try:
        emprestimo.delete()
        flash("Empréstimo removido com sucesso!", "success")

    except Exception:
        db.session.rollback()
        flash("Erro ao remover empréstimo.", "error")

    return redirect(url_for("emprestimo.listar"))

templates/emprestimos/emprestimos.html
{% extends 'base.html' %}
{% block titulo %} Empréstimos {% endblock %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/emprestimos/emprestimos.css') }}">
{% endblock %}

{% block conteudo %}
<main>

    <h1>Empréstimos Registrados</h1>

    {% include 'includes/mensagens.html' %}

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Usuário</th>
                <th>Item</th>
                <th>Retirada</th>
                <th>Devolução</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            {% for e in emprestimos %}
            <tr>
                <td>{{ e.id }}</td>
                <td>{{ e.user.nome }}</td>
                <td>{{ e.item.nome }}</td>
                <td>{{ e.data_emprestimo.strftime("%d/%m/%Y %H:%M") }}</td>
                <td>{{ e.data_devolucao.strftime("%d/%m/%Y %H:%M") if e.data_devolucao else "-" }}</td>
                <td>{{ e.status }}</td>

                <td>

                    {% if e.user_id == current_user.id or current_user.is_admin() %}
                        {% if e.status != "devolvido" %}
                        <form action="{{ url_for('emprestimo.devolver', id=e.id) }}" 
                              method="POST" 
                              style="display:inline;">
                            <button class="btn btn-devolver" type="submit">
                                Devolver
                            </button>
                        </form>
                        {% endif %}

                        {% if current_user.is_admin() %}
                            <form action="{{ url_for('emprestimo.remover', id=e.id) }}" 
                                  method="POST" 
                                  style="display:inline;">
                                <button class="btn-small danger" type="submit">
                                    Remover
                                </button>
                            </form>
                        {% endif %}            
                    {% else %}

                        <span style="color: rgb(20, 19, 19); font-size: 0.9rem;">
                            Não é seu empréstimo
                        </span>
                    {% endif %}

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</main>
{% endblock %}