models/itens.py
from models import db

class Item(db.Model):
    __tablename__ = "tb_itens"
    id = db.Column("itm_id", db.Integer, primary_key=True)
    nome = db.Column("itm_nome", db.String(150))
    categoria = db.Column("itm_categoria", db.String(50), nullable = True)
    quantidade = db.Column("itm_quantidade", db.Integer, nullable=False)

    @classmethod
    def buscar(cls, termo=None):
        query = cls.query

        if termo:
            query = query.filter(
                cls.nome.ilike(f"%{termo}%")
            )

        return query.order_by(cls.nome).all()


    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()
        return self

    @classmethod
    def get(cls, id):
        return cls.query.get(id)

    @classmethod
    def all(cls):
        return cls.query.all()

    def update(self, nome=None, categoria=None, quantidade=None):
        if nome:
            self.nome = nome
        if categoria:
            self.categoria = categoria
        if quantidade is not None:
            self.quantidade = quantidade

        db.session.commit()
        return self


    def delete(self):
        db.session.delete(self)
        db.session.commit()

controllers/emprestimo_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from datetime import date, datetime, timezone

from decorators import admin_required
from models.emprestimos import Emprestimo
from models.users import User
from models.itens import Item
from storage import db

emprestimo_bp = Blueprint("emprestimo", __name__, url_prefix="/emprestimos", template_folder="templates/emprestimos")

@emprestimo_bp.route("/")
@login_required
def listar():

    if current_user.is_admin():
        emprestimos = Emprestimo.all()
    else:
        emprestimos = Emprestimo.query.filter_by(user_id =current_user.id).all()

    return render_template("emprestimos/emprestimos.html", emprestimos=emprestimos, User=User,Item=Item)

@emprestimo_bp.route("/adicionar", methods=["POST"])
@login_required
def adicionar():
    LIMITE_EMPRESTIMOS = 3

    item_id = request.form.get("item_id")

    if not item_id:
        flash("Item inválido.", "error")
        return redirect(url_for("item.itens"))    

    total_ativos = Emprestimo.ativos_por_usuario(current_user.id)

    if total_ativos >= LIMITE_EMPRESTIMOS:
        flash(f"Você atingiu o limite de {LIMITE_EMPRESTIMOS} empréstimos ativos.","error") 
        return redirect(url_for("item.itens"))

    item = Item.get(int(item_id))

    if not item or item.quantidade <= 0:
        flash("Item indisponível.", "error")
        return redirect(url_for("item.itens"))

    emprestimo = Emprestimo(
        user_id=current_user.id,
        item_id=item_id,
        status="pendente"
    )
    emprestimo.save()

    item.update(quantidade=item.quantidade - 1)

    flash("Empréstimo registrado com sucesso!", "success")
    return redirect(url_for("emprestimo.listar"))

@emprestimo_bp.route("/devolver/<int:id>", methods=["POST"])
@login_required
def devolver(id):
    emp = Emprestimo.get(id)
    if not emp:
        flash("Empréstimo não encontrado.", "error")
        return redirect(url_for("emprestimo.listar"))

    if emp.user_id != current_user.id:
        flash("Você não pode devolver um empréstimo de outro usuário!", "error")
        return redirect(url_for("emprestimo.listar"))

    item = Item.get(emp.item_id)
    if not item:
        flash("Item associado não encontrado!", "error")
        return redirect(url_for("emprestimo.listar"))

    emp.update(
        status="devolvido",
        data_devolucao=datetime.now()
    )

    item.update(quantidade=item.quantidade + 1)

    flash("Item devolvido com sucesso!", "success")
    return redirect(url_for("emprestimo.listar"))


@emprestimo_bp.route("/remover/<int:id>", methods=["POST"])
@admin_required
def remover(id):
    emprestimo = Emprestimo.get(id)
    if not emprestimo:
        flash("Empréstimo não encontrado.", "error")
        return redirect(url_for("emprestimo.listar"))

    try:
        emprestimo.delete()
        flash("Empréstimo removido com sucesso!", "success")

    except Exception:
        db.session.rollback()
        flash("Erro ao remover empréstimo.", "error")

    return redirect(url_for("emprestimo.listar"))

controllers/itens_controller.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required
from models.itens import Item
from decorators import admin_required

item_bp = Blueprint("item", __name__, url_prefix='/itens', template_folder='templates/itens')

@item_bp.route("/")
@login_required
def itens():
    q = request.args.get("q", "").strip()

    itens = Item.buscar(q)

    return render_template("itens/itens.html",itens=itens,q=q)

@item_bp.route("/adicionar", methods = ["GET", "POST"])
@admin_required
def adicionar():
    if request.method == "POST":
        item = Item(nome=request.form["nome"], categoria=(request.form["categoria"]), quantidade = int(request.form["quantidade"], 0))

        item.save()
        flash("Produto adicionado com sucesso!", "success")
        return redirect(url_for("item.itens"))
    
    return render_template("itens/adicionar.html")

@item_bp.route("/editar/<int:id>", methods = ["GET", "POST"])
@admin_required
def editar(id):
    i = Item.get(id)
    if not i:
        flash("Item não encontrado!", "error")
        return redirect(url_for("item.itens"))

    if request.method == "POST":
        i.update(nome=request.form.get("nome"),categoria=(request.form.get("categoria")),quantidade=int(request.form.get("quantidade", 0)))
        flash("Item editado!", "success")
        return redirect(url_for("item.itens"))

    return render_template('itens/editar.html', item=i)

@item_bp.route('/deletar/<int:id>', methods = ["POST"])
@admin_required
def remover(id):
    i = Item.get(id)

    if i:
        try:
            i.delete()
            flash("Item removido com sucesso!", "success")
        except:
            flash(f"Não foi possível remover este item.", "error")
    else:
        flash(f"Item não encontrado, tente novamente.", "error")
    return redirect(url_for("item.itens"))

templates/itens/adicionar.html
{% extends 'base.html' %}
{% block titulo %} Adicionar Item {% endblock %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/items/items_form.css') }}">
{% endblock %}

{% block conteudo %}
<main>
    <h1>Adicionar Item</h1>

    {% include 'includes/mensagens.html' %}

    <form action="{{ url_for('item.adicionar') }}" method="POST">

        <label>Nome</label>
        <input type="text" name="nome" required>

        <label>Categoria</label>
        <input type="text" name="categoria">

        <label>Quantidade</label>
        <input type="number" name="quantidade" min="0" required>

        <button type="submit" class="btn">Cadastrar</button>
    </form>
</main>
{% endblock %}

templates/itens/editar.html
{% extends 'base.html' %}
{% block titulo %} Editar Item {% endblock %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/items/items_form.css') }}">
{% endblock %}

{% block conteudo %}
<main>
    <h1>Editar Item</h1>

    {% include 'includes/mensagens.html' %}

    <form action="{{ url_for('item.editar', id=item.id) }}" method="POST">

        <label>Nome</label>
        <input type="text" name="nome" value="{{ item.nome }}" required>

        <label>Categoria</label>
        <input type="text" name="categoria" value="{{ item.categoria }}">

        <label>Quantidade</label>
        <input type="number" name="quantidade" min="0" value="{{ item.quantidade }}" required>

        <button type="submit" class="btn">Salvar</button>
    </form>
</main>
{% endblock %}

templates/itens/itens.html
{% extends 'base.html' %}
{% block titulo %} Lista de Itens {% endblock %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/items/items.css') }}">
{% endblock %}

{% block conteudo %}
<main>
    <h1>Itens Cadastrados</h1>

    {% include 'includes/mensagens.html' %} 

    {% if current_user.is_admin() %}
        <a class="btn" href="{{ url_for('item.adicionar') }}">Adicionar Item</a>
    {% endif %}
    
    <form method="get" class="busca-itens">
        <input type="text" name="q"placeholder="Buscar item" value="{{ q }}">
        <button type="submit">Buscar</button>
    </form>


    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Quantidade</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            {% for item in itens %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.nome }}</td>
                <td>{{ item.categoria }}</td>
                <td>{{ item.quantidade }}</td>
                <td>

                    {% if current_user.is_admin() %}
                        <a class="btn-small" href="{{ url_for('item.editar', id=item.id) }}">Editar</a>
                    
                        <form action="{{ url_for('item.remover', id=item.id) }}" method="POST" style="display:inline;">
                            <button class="btn-small danger" type="submit">Remover</button>
                        </form>
                    {% endif %}

                    <form action="{{ url_for('emprestimo.adicionar') }}" method="POST">
                        <button type="submit" name="item_id" value="{{ item.id }}" class="btn-small">
                            Pegar Emprestado
                        </button>
                    </form>

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</main>
{% endblock %}