models/users.py
# models/users.py
from models import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

class User(UserMixin, db.Model):
    __tablename__ = "tb_usuarios"
    id = db.Column("usr_id", db.Integer, primary_key=True)
    email = db.Column("usr_email", db.String(150), unique=True, nullable=False)
    senha_hash = db.Column("usr_senha", db.String(200), nullable=False)
    nome = db.Column("usr_nome", db.String(150))
    cpf = db.Column("usr_cpf", db.String(14))
    perfil = db.Column("usr_perfil", db.String(20), default="usuario")

    def is_admin(self):
        return self.perfil == "admin"

    @classmethod
    def get(cls, user_id):
        return cls.query.get(user_id)
    
    @classmethod
    def all(cls):
        return cls.query.all()
    
    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()
        return self

    def update(self, email=None, senha=None, nome=None, cpf=None):
        if email:
            self.email = email
        if senha:
            self.senha_hash = generate_password_hash(senha)
        if nome:
            self.nome = nome
        if cpf:
            self.cpf = cpf
        db.session.commit()
        return self
    
    @classmethod
    def delete(cls, user_id):
        usuario = cls.query.get(user_id)
        if not usuario:
            return False

        db.session.delete(usuario)
        db.session.commit()
        return True

controllers/users_controller.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, login_user, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash

from models.users import User

user_bp = Blueprint("user", __name__, url_prefix="/users", template_folder="templates/users")

@user_bp.route("/")
@login_required
def listar():
    usuarios = User.all()
    print(current_user.perfil)
    return render_template("users/usuarios.html", usuarios=usuarios)

@user_bp.route("/editar/<int:id>", methods=["GET", "POST"])
@login_required
def editar(id):
    u = User.get(id)

    if not u:
        flash("Usuário não encontrado!", "error")
        return redirect(url_for("user.listar"))

    if request.method == "POST":

        try:
            u.update(
                nome=request.form.get("nome"),
                cpf=request.form.get("cpf"),
                email=request.form.get("email"),
                senha=request.form.get("senha") 
            )
            flash("Usuário atualizado com sucesso!", "success")
        except:
            flash("Erro ao atualizar usuário.", "error")

        return redirect(url_for("user.listar"))

    return render_template("users/editar.html", user=u)

@user_bp.route("/deletar/<int:id>", methods=["POST"])
@login_required
def deletar(id):

    try:
        if User.delete(id):
            flash("Usuário removido com sucesso!", "success")
        else:
            flash("Usuário não encontrado.", "error")

    except:
        flash("Não foi possível remover o usuário.", "error")

    return redirect(url_for("user.listar"))

templates/users/editar.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/users/editar.css') }}">
{% endblock %}

{% block titulo %} Editar Usuário {% endblock %}

{% block conteudo %}
<main>

    {% include 'includes/mensagens.html' %}

    <h1>Editar Usuário</h1>

    <form method="POST">
        <label>Nome</label>
        <input type="text" name="nome" value="{{ user.nome }}" required>

        <label>CPF</label>
        <input type="text" name="cpf" value="{{ user.cpf }}">

        <label>Email</label>
        <input type="email" name="email" value="{{ user.email }}" required>

        <label>Senha (deixe vazio para manter a atual)</label>
        <input type="password" name="senha">

        <button type="submit" class="btn-submit">Salvar Alterações</button>
    </form>

    <a class="voltar" href="{{ url_for('user.listar') }}">Voltar</a>

</main>
{% endblock %}

templates/users/usuarios.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/users/usuarios.css') }}">
{% endblock %}

{% block titulo %} Lista de Usuários {% endblock %}

{% block conteudo %}
<main>

    {% include 'includes/mensagens.html' %}

    <h1>Gerenciamento de Usuários</h1>
    <p>Veja, edite ou remova usuários cadastrados no sistema.</p>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Ações</th>
            </tr>
        </thead>

        <tbody>
            {% for u in usuarios %}
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.nome }}</td>
                <td>{{ u.cpf }}</td>
                <td>{{ u.email }}</td>


                <td class="acoes">
                    {% if u.id == current_user.id %}
                        <a class="btn-small edit" href="{{ url_for('user.editar', id=u.id) }}">Editar</a>
                    {% endif %}

                    {% if u.id == current_user.id or current_user.is_admin() %}
                        <form action="{{ url_for('user.deletar', id=u.id) }}" method="POST">
                            <button type="submit" class="btn-small delete">Remover</button>
                        </form>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}
        </tbody>

    </table>
</main>
{% endblock %}